# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-21 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['variety']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['locale']},
        ),
    ]
