# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-21 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallary', '0004_auto_20190721_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
